### ISSUE TITLE
download_bc03_ssp.sh vs what is looked for by fastpp

### ISSUE THREAD

**Issue by themiyan** [cschreib/fastpp#13]
Hi!!! 

In the download script for the models the final names are in the format of 
*.ised_ASCII

However, when the code is executed libraries are still expected in this format:
fastpp/share/libraries/ised_exp.hr/bc03_hr_ch_z004_ltau8.5.ised

**Comment by cschreib** [comment]
Hi Themiya. Sorry it took me a year to notice this... I hope you haven't been blocked for so long!

To answer your question, the `.ised` files are expected for pre-gridded star formation histories, and `.ised_ASCII` or `.ised_ASCII.fits` for SSPs. The download script is only meant to download SSPs, hence the extension you get.

If you are still having issue with this, let me know.

**Comment by themiyan** [comment]
aha got it. Thanks Corentin. 
It was more of a curiosity question since I found some models were missing from FAST downloads in Mariska's webpage.
