### ISSUE TITLE
Getting error while running "make install"

### ISSUE THREAD

**Issue by Najmeh-Emami** [cschreib/fastpp#14]
Hello,

I am trying to install fast++ on my mac, which has an updated XCode, C++ compiler, git, and CMake. However, while I run the "make install" command, I get an error saying :

".../fastpp/external/cfitsio/group.c:5476:3: error: implicit declaration of function 'getcwd' is invalid in C99 [-Werror,-Wimplicit-function-declaration]"

I wonder whether this error is related to any incompatibility between the recent Mac version (macOS 11.4) and the current fast++ code or there is an issue with my installations.

Any help on this is really appreciated!

**Comment by cschreib** [comment]
Thanks for reporting this. It looks like a configuration issue with CFITSIO. I have committed a fix on the master branch here, that should get you going until they fix the problem upstream. Please let me know if the fix worked for you or not!

**Comment by Najmeh-Emami** [comment]
Thank you so much for the help! It fixed the problem and fast++ is installed now!

**Comment by cschreib** [comment]
Great! Happy fitting :)
