### ISSUE TITLE
Unavailable library ised_exp.pr

### ISSUE THREAD

**Issue by ipmcconachie** [cschreib/fastpp#3]
When I run FAST++, I get the following error:

>error: could not read data in library file '~/Software/fastpp/share/libraries/ised_exp.pr/bc03_pr_ch_z02_ltau7.0.ised'
>error: could not open file
>error: the file is probably corrupted, try re-downloading it

The libraries available from Mariska Kriek's website are ised_del.lr, ised_del.hr, ised_tru.hr, and ised_exp.**hr**, but there is no ised_exp.**pr** as far as I can tell.

**Comment by cschreib** [comment]
You are correct. I do have an ```ised_exp.pr``` library sitting on my hard drive but I have no idea where it came from originally... It seems to have been used for most major surveys though (UltraVISTA, 3DHST and ZFOURGE), I wonder why it's not on Mariska's website. You can try to contact her about it. In the mean time I have uploaded it here:
https://www.dropbox.com/s/umo8e03veyaz2r2/ised_exp.pr.tar.gz?dl=1

NB: The difference between the "pr", "hr" and "lr" libraries should only be one of computing time, the outputs should be mostly unchanged. The "pr" libraries have a lower spectral resolution than the "hr" ones, which reduces the computing time (and a lower resolution is OK when only photometry is used in the fit). So at the price of a slightly slower (but more accurate!) fit, you could as well use the "hr" libraries.

**Comment by lboogaard** [comment]
The `ised_exp.pr` comes with the download of `FAST_v1.0` itself - only the larger libraries have to be downloaded separately.

**Comment by cschreib** [comment]
Ah! I guess this tells you how long ago I last downloaded and used FAST :) Thanks Leindert for the precision! I'll edit the README to include this information.
