### ISSUE TITLE
Investigating best-fit SEDs

### ISSUE THREAD

**Issue by themiyan** [cschreib/fastpp#6]
The `INTRINSIC_BEST_FIT` option is expected to output a text file with wavelength, best-fit SED, and intrinsic best-fit SED. However,  `fl` and  `fl_nodust` are both the same and it looks like it is the intrinsic SED that is getting attributed to both the columns here.

**Comment by cschreib** [comment]
Hmm, I don't see anything obvious in the code, and I just tested it here and it works. Are you sure your galaxy does not have a best fit Av = 0 ? In that case obviously there should be no difference between the SED with/without dust :)

**Comment by themiyan** [comment]
aha, this was to do with an old build. I forgot I had to rebuild after pulling from git, silly mistake. I think the build I had was pretty old.

**Comment by themiyan** [comment]
can I follow up on the new build regarding Z? :)

`METAL          = [0.004, 0.02, 0.05, 0.008]  `

In the past commit this would use all SSPs in this array, but now it seems it uses only the first value specified in the array.

**Comment by cschreib** [comment]
FYI: It's better to open a new issue for un-related problems ;) 

As for your problem, I just tried running a fit with an array of metallicities and they were all considered in the fit. Are you sure the ```METAL``` option is not being re-defined twice in the param file? When running the program, do you see a line like this printed in the terminal:
```
note: fitting a grid of XXX templates (ntau=XX,nmetal=4,nage=XX,nav=XX,nz=XXX)
```
... with ```nmetal=4``` ?
