### ISSUE TITLE
valid dust laws

### ISSUE THREAD

**Issue by brojonat** [cschreib/fastpp#8]
Running some initial tests and noticed an issue with the valid dust laws in fast++-read_input.cpp:
```
note: this is FAST++ version '1.2'
error: unknown dust law 'mw'
error: possible values: {calzetti, mz, noll, kc}
```

**Comment by cschreib** [comment]
Thanks for reporting the bug! This should now be fixed on the master branch. Please let me know if the problem is not actually solved for you.
